In [1]:
import pandas as pd

In [2]:
a = pd.read_excel (r'C:\Users\noza\Downloads\Term2-2\DBP221_421 A.Uuganbayar\Week7_Store Data Sample, order.xlsx')
print (a)

             Order ID     Order Date  Customer ID         Segment  \
0   'CA-2016-152156',  '11.08.2016',  'EB-13930',     'Хувь хүн',
1   'CA-2016-152156',  '11.08.2016',  'EB-13930',     'Хувь хүн',
2   'CA-2016-138688',  '06.12.2016',  'MO-17950',  'Байгууллага',
3   'US-2015-108966',  '10.11.2015',  'JO-15550',     'Хувь хүн',
4   'US-2015-108966',  '10.11.2015',  'JO-15550',     'Хувь хүн',
..                ...            ...          ...             ...
95  'US-2017-109484',  '11.06.2017',  'JR-15700',       'Гишүүн',
96  'CA-2017-161018',  '11.09.2017',  'AJ-10945',       'Гишүүн',
97  'CA-2017-157833',  '06.17.2017',  'BM-11575',     'Хувь хүн',
98  'CA-2016-149223',  '09.06.2016',  'CV-12805',  'Байгууллага',
99  'CA-2016-158568',  '08.29.2016',  'DK-12835',       'Гишүүн',

          Region                            Category  \
0    'Баянзүрх',                   'Чихэр, печенье',
1    'Баянзүрх',           'OO ийн цаас, сальфетка',
2     'Хан-Уул',                   'Чихэр, печенье',
3    'Баянзүрх',                        'Хиам бууз',
4    'Баянзүрх',                         'Ундаа ус',
..           ...                                 ...
95    'Хан-Уул',  'Компот варенье, хүүхдийн тэжээл',
96  'Сүхбаатар',                       'Самар чипс',
97    'Хан-Уул',             'Набор, шоколад, бохь',
98  'Чингэлтэй',                        'Архи пиво',
99  'Чингэлтэй',                     'Бэлэн гоймон',

                  Product Name  Price Quantity Discount   Sales
0        'Shokolinsen 250 гр',  3300,       2,       0,   6600,
1       'Хэрэглээ 00ийн цаас',   500,       3,       0,   1500,
2   'Алимтай жигнэмэг 230 гр',  3100,       2,       0,   6200,
3       'Золотой янта 500 гр',  2800,       5,       0,  14000,
4              'Punch 450 мл',  1150,       2,       0,   2300,
..                         ...    ...      ...      ...     ...
95            'Hainich нухаш',  3300,       1,    0.03,   3201,
96          'Lays чипс 80 гр',  2300,       7,    0.03,  15617,
97           'Монстров 23 гр',   500,       3,       0,   1500,
98              'Арвай 0.100',  2000,       6,       0,  12000,
99     'Тэйсти гоймон 110 гр',  1800,       7,    0.03,  12222,

[100 rows x 11 columns]

In [6]:
#1 Эхний 10 мөрийг сонгож авна уу.
a.iloc[:11, :11]

,Order ID,Order Date,Customer ID,Segment,Region,Category,Product Name,Price,Quantity,Discount,Sales
0,"'CA-2016-152156',","'11.08.2016',","'EB-13930',","'Хувь хүн',","'Баянзүрх',","'Чихэр, печенье',","'Shokolinsen 250 гр',","3300,","2,","0,","6600,"
1,"'CA-2016-152156',","'11.08.2016',","'EB-13930',","'Хувь хүн',","'Баянзүрх',","'OO ийн цаас, сальфетка',","'Хэрэглээ 00ийн цаас',","500,","3,","0,","1500,"
2,"'CA-2016-138688',","'06.12.2016',","'MO-17950',","'Байгууллага',","'Хан-Уул',","'Чихэр, печенье',","'Алимтай жигнэмэг 230 гр',","3100,","2,","0,","6200,"
3,"'US-2015-108966',","'10.11.2015',","'JO-15550',","'Хувь хүн',","'Баянзүрх',","'Хиам бууз',","'Золотой янта 500 гр',","2800,","5,","0,","14000,"
4,"'US-2015-108966',","'10.11.2015',","'JO-15550',","'Хувь хүн',","'Баянзүрх',","'Ундаа ус',","'Punch 450 мл',","1150,","2,","0,","2300,"
5,"'CA-2014-115812',","'06.09.2014',","'RH-19600',","'Хувь хүн',","'Хан-Уул',","'Жимс ногоо',","'Помидор том',","4000,","7,","0,","28000,"
6,"'CA-2014-115812',","'06.09.2014',","'RH-19600',","'Хувь хүн',","'Хан-Уул',","'Гурил будаа',","'Слава хивэг 400 гр',","750,","4,","0,","3000,"
7,"'CA-2014-115812',","'06.09.2014',","'RH-19600',","'Хувь хүн',","'Хан-Уул',","'Бичиг хэрэг',","'Үзгэн бал арилгадаг',","2500,","6,","0,","15000,"
8,"'CA-2014-115812',","'06.09.2014',","'RH-19600',","'Хувь хүн',","'Хан-Уул',","'OO ийн цаас, сальфетка',","'Lady 20 ш',","2200,","3,","0,","6600,"
9,"'CA-2014-115812',","'06.09.2014',","'RH-19600',","'Хувь хүн',","'Хан-Уул',","'Ундаа ус',","'370 Жүүс 370 мл',","850,","5,","0,","4250,"
10,"'CA-2014-115812',","'06.09.2014',","'RH-19600',","'Хувь хүн',","'Хан-Уул',","'OO ийн цаас, сальфетка',","'Саль ариун 30 ш',","2200,","9,","0,","19800,"

In [9]:
#2 78-88 дугаар мөрөнд байгаа мэдээллээс Product Name, Sales багануудыг харуулна уу.
a.loc[78:88, ['Product Name', 'Sales']]

                              Product Name   Sales
78          'Чихэр кг Конфет Кино 400 гр',  15000,
79                        'Cocoro 100 гр',   2300,
80                     '3н өнгийн алчуур',   3300,
81           'Оргилуун ус жимстэй 500 мл',   5250,
82                     'Видан зөгийн бал',   3300,
83                      'Сор жүүс 200 мл',   3500,
84                 'Гурвалжин шоко 22 гр',   1746,
85                        'Гоё тетра 1 л',   3200,
86                     'Хараа 0.75 цэвэр',  11500,
87              'Шпрот урт татдаг 190 гр',   7000,
88  'Bagro хүрэн манжингийн салат 500 мл',  14938,

In [12]:
#3 Quantity болон Sales баганыг сонгож авна уу.
a.loc[0:99, ['Quantity', 'Sales']]

   Quantity   Sales
0        2,   6600,
1        3,   1500,
2        2,   6200,
3        5,  14000,
4        2,   2300,
..      ...     ...
95       1,   3201,
96       7,  15617,
97       3,   1500,
98       6,  12000,
99       7,  12222,

[100 rows x 2 columns]

In [33]:
#4 Quantity болон Sales баганын нийлбэрүүдийг харуулна уу.
e = a['sum of Q and S'] = a['Quantity'] + a['Sales']
e

0      2,6600,
1      3,1500,
2      2,6200,
3     5,14000,
4      2,2300,
        ...
95     1,3201,
96    7,15617,
97     3,1500,
98    6,12000,
99    7,12222,
Length: 100, dtype: object

In [17]:
#5 Product Name баганыг сонгож авна уу.
a['Product Name']

0          'Shokolinsen 250 гр',
1         'Хэрэглээ 00ийн цаас',
2     'Алимтай жигнэмэг 230 гр',
3         'Золотой янта 500 гр',
4                'Punch 450 мл',
                 ...
95              'Hainich нухаш',
96            'Lays чипс 80 гр',
97             'Монстров 23 гр',
98                'Арвай 0.100',
99       'Тэйсти гоймон 110 гр',
Name: Product Name, Length: 100, dtype: object

In [24]:
#6 Product Name баганын давхардаагүй утгуудыг харуулна уу.
b = a['Product Name'].unique()
print(b)

["'Shokolinsen 250 гр'," "'Хэрэглээ 00ийн цаас',"
 "'Алимтай жигнэмэг 230 гр'," "'Золотой янта 500 гр'," "'Punch 450 мл',"
 "'Помидор том'," "'Слава хивэг 400 гр'," "'Үзгэн бал арилгадаг',"
 "'Lady 20 ш'," "'370 Жүүс 370 мл'," "'Саль ариун 30 ш',"
 "'Pysio 300 мл'," "'A vodka 0.5'," "'Өгөөж танзуур',"
 "'Vita жимстэй ус 510 мл'," "'Алое шилтэй 180 мл'," "'Power 400 g',"
 "'Пломбир на сливках 80 гр савтай'," "'Удон гоймон ууттай',"
 "'M&M 45 гр'," "'Витафит ус 500 мл'," "'Памперс №4',"
 "'Solpro майонез 3 л 67 %'," "'Магнат 80 гр',"
 "'Хувцасны өлгүүр 5 ш алаг'," "'Шингэн чихэр'," "'Akuku резин 90 гр',"
 "'Сахлын татуурга Gilette'," "'Русский сахар 250 гр',"
 "'Бэлэн гоймон төмстэй'," "'Хүслийн ундаа 500 мл',"
 "'Arizona лаазтай 680 мл'," "'Jacobs кофе'," "'Өглөө сүү',"
 "'Амт чипс 55 гр'," "'Эгоист 65 гр'," "'Colgate total 100 гр',"
 "'Слава гурвалжин будаа 650 гр'," "'Хараа 0.75 цэвэр',"
 "'Вигора 200 гр'," "'Давс 1 кг'," "'Mini cracker 350 гр',"
 "'Тоник лаазтай 330 мл'," "'Tide 450 гр авто',"
 "'Paldo king noodle 110 гр'," "'Цесна 25 кг'," "'Appetita плова',"
 "'Саль ариун 100 ш'," "'Слава каш 1 кг'," "'Моя семъя 1 л',"
 "'Зуун наст 1.25 мл'," "'Мандарин'," "'Appetita будаатай хуурга',"
 "'Цэвэрхэн 00ийн цаас'," "'Siesta үзэм 200 гр',"
 "'Махеевь салатны 400 мл'," "'Selpak 2 хайрцаг'," "'Oleina тос 1 л',"
 "'Чихэр кг Кокос 400 гр'," "'Nivea тос 50 мл'," "'Омо 100 гр',"
 "'Өгөөж вафли'," "'Head & Shoulders 400 мл'," "'Жимстэй чокопай 6 ш',"
 "'Соёолж 2.5 л'," "'Тэргүүн 0.5'," "'Витсамо ус 500 мл',"
 "'Дашида 50 гр'," "'Заантай будаа 5 кг'," "'Lays чипс 80 гр',"
 "'Хавиргатай рагу 454 гр'," "'Хутга 1 ш'," "'Нандин чавга 250 гр',"
 "'Чинжүү'," "'Чихэр кг Конфет Кино 400 гр'," "'Cocoro 100 гр',"
 "'3н өнгийн алчуур'," "'Оргилуун ус жимстэй 500 мл',"
 "'Видан зөгийн бал'," "'Сор жүүс 200 мл'," "'Гурвалжин шоко 22 гр',"
 "'Гоё тетра 1 л'," "'Шпрот урт татдаг 190 гр',"
 "'Bagro хүрэн манжингийн салат 500 мл'," "'Цагаан самар 50 гр',"
 "'Махны мод дугуй'," "'Биг ланч 110 гр савтай'," "'Custard 6 ш',"
 "'Алтантүрүү 0.5'," "'Фифти фифти 180 гр'," "'Hainich нухаш',"
 "'Монстров 23 гр'," "'Арвай 0.100'," "'Тэйсти гоймон 110 гр',"]

In [25]:
#7 Product Name баганын давхардаагүй утгууд нийт хэд байгааг тоолж харуулна уу.
a['Product Name'].nunique()

94

In [29]:
#8 Product Name баганын давхардсан утгуудыг харуулна уу.
c = a["Product Name"].duplicated()
c

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96     True
97    False
98    False
99    False
Name: Product Name, Length: 100, dtype: bool

In [30]:
#9 Order ID баганын давхардаагүй утгууд нийт хэд байгааг тоолж харуулна уу.
a['Order ID'].nunique()

50

In [34]:
#10 Бараа тус бүрээс хэдэн ширхэгийг зарсаныг харуулна уу.
d = a.groupby(['Product Name']).sum()
d

,Order ID,Order Date,Customer ID,Segment,Region,Category,Price,Quantity,Discount,Sales,sum of Q and S
Product Name,,,,,,,,,,,
"'370 Жүүс 370 мл',","'CA-2014-115812',","'06.09.2014',","'RH-19600',","'Хувь хүн',","'Хан-Уул',","'Ундаа ус',","850,","5,","0,","4250,","5,4250,"
"'3н өнгийн алчуур',","'CA-2016-127208',","'06.12.2016',","'LM-17065',","'Байгууллага',","'Баянзүрх',","'Гэр ахуй',","1100,","3,","0,","3300,","3,3300,"
"'A vodka 0.5',","'CA-2017-114412',","'04.15.2017',","'GB-14530',","'Хувь хүн',","'Баянзүрх',","'Архи пиво',","9000,","3,","0,","27000,","3,27000,"
"'Akuku резин 90 гр',","'CA-2016-121755',","'01.16.2016',","'AF-10885',","'Хувь хүн',","'Хан-Уул',","'Чихэр, печенье',","1500,","3,","0,","4500,","3,4500,"
"'Appetita будаатай хуурга',","'CA-2016-105816','US-2017-118038',","'12.11.2016','12.09.2017',","'SR-20740','BO-11425',","'Байгууллага','Байгууллага',","'Сүхбаатар','Чингэлтэй',","'Амтлагч','Амтлагч',","350,350,","5,3,","0,0,","1750,1050,","5,1750,3,1050,"
...,...,...,...,...,...,...,...,...,...,...,...
"'Эгоист 65 гр',","'CA-2016-117590',","'12.08.2016',","'JS-15595',","'Байгууллага',","'Чингэлтэй',","'Зайрмаг',","900,","5,","0,","4500,","5,4500,"
"'Үзгэн бал арилгадаг',","'CA-2014-115812',","'06.09.2014',","'RH-19600',","'Хувь хүн',","'Хан-Уул',","'Бичиг хэрэг',","2500,","6,","0,","15000,","6,15000,"
"'Өглөө сүү',","'CA-2017-107727',","'10.19.2017',","'BC-11125',","'Гишүүн',","'Чингэлтэй',","'УНДАА УС',","2600,","3,","0.03,","7566,","3,7566,"
"'Өгөөж вафли',","'CA-2015-135545',","'11.24.2015',","'EB-13870',","'Хувь хүн',","'Хан-Уул',","'Чихэр, печенье',","1950,","6,","0,","11700,","6,11700,"
"'Өгөөж танзуур',","'CA-2016-161389',","'12.05.2016',","'PW-19030',","'Хувь хүн',","'Хан-Уул',","'Талх, нарийн боов',","3000,","3,","0,","9000,","3,9000,"

In [36]:
#11 Хамгийн өндөр дүнтэй борлуулалтыг (Order ID) олно уу.
a.loc[:,['Order ID']].max()

Order ID    'US-2017-156909',
dtype: object

In [37]:
#12 Хамгийн өндөр дүнтэй зарагдсан барааг (Sales) олно уу.
a.loc[:,['Sales']].max()

Sales    9600,
dtype: object